spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: root
    password: password

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

server.port: 8080